// src/techStackData.js
export const techStackData = [
    { name: 'HTML5', icon: 'fab fa-html5', color: '#e34c26', bgColor: 'bg-orange-100' },
    { name: 'JavaScript', icon: 'fab fa-js', color: '#f7df1e', bgColor: 'bg-yellow-100' },
    { name: 'React', icon: 'fab fa-react', color: '#61dafb', bgColor: 'bg-blue-100' },
    { name: 'Vue', icon: 'fab fa-vuejs', color: '#42b883', bgColor: 'bg-green-100' },
    { name: 'ECharts', icon: 'fas fa-chart-line', color: '#3398db', bgColor: 'bg-blue-100' },
    { name: 'CSS3', icon: 'fab fa-css3-alt', color: '#264de4', bgColor: 'bg-purple-100' },
    { name: 'TypeScript', icon: 'fab fa-js-square', color: '#3178c6', bgColor: 'bg-blue-100' },
    { name: 'Spring Boot', icon: 'fas fa-leaf', color: '#6db33f', bgColor: 'bg-green-200' },
    { name: 'Nginx', icon: 'fas fa-server', color: '#009639', bgColor: 'bg-blue-100' },
    { name: 'Redis', icon: 'fas fa-database', color: '#d82c20', bgColor: 'bg-gray-100' },
    { name: 'RabbitMQ', icon: 'fas fa-envelope', color: '#ff6600', bgColor: 'bg-blue-100' },
    { name: 'Java EE', icon: 'fab fa-java', color: '#007396', bgColor: 'bg-yellow-100' },
    { name: 'MyBatis', icon: 'fas fa-database', color: '#dc382d', bgColor: 'bg-red-100' },
    { name: 'Node.js', icon: 'fab fa-node-js', color: '#68a063', bgColor: 'bg-blue-100' },
    { name: 'JSP', icon: 'fas fa-file-code', color: '#4a4a4a', bgColor: 'bg-gray-200' },
    { name: 'MySQL', icon: 'fas fa-database', color: '#00758f', bgColor: 'bg-blue-100' },
    { name: 'MongoDB', icon: 'fas fa-database', color: '#4caf50', bgColor: 'bg-green-100' },
    { name: 'SQL Server', icon: 'fas fa-database', color: '#a91d22', bgColor: 'bg-purple-100' },
    { name: 'Git', icon: 'fab fa-git', color: '#f05032', bgColor: 'bg-gray-100' },
    { name: 'Docker', icon: 'fab fa-docker', color: '#2496ed', bgColor: 'bg-blue-100' },
    { name: 'SVN', icon: 'fab fa-sourcetree', color: '#0040ff', bgColor: 'bg-gray-100' },
    { name: 'NPM', icon: 'fab fa-npm', color: '#cb3837', bgColor: 'bg-red-100' },
    { name: 'RESTful API', icon: 'fas fa-network-wired', color: '#6366f1', bgColor: 'bg-indigo-100' },
    { name: 'JWT', icon: 'fas fa-key', color: '#f4b400', bgColor: 'bg-yellow-100' },
];
